example_event = {
	'version': '1.0',
	'resource': '/redirect/{proxy+}',
	'path': '/default/redirect/google',
	'httpMethod': 'GET',
	'headers': {
		'Content-Length': '0',
		'Host': 'an_api_id.execute-api.aws_region.amazonaws.com',
		'User-Agent': 'a_user_agent',
		'X-Amzn-Trace-Id': 'an_amzn_trace_id',
		'X-Forwarded-For': 'an_ip_address',
		'X-Forwarded-Port': '443',
		'X-Forwarded-Proto': 'https',
		'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
		'accept-encoding': 'gzip, deflate, br',
		'accept-language': 'en-US,en;q=0.9',
		'sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"',
		'sec-ch-ua-mobile': '?0',
		'sec-ch-ua-platform': '"Windows"',
		'sec-fetch-dest': 'document',
		'sec-fetch-mode': 'navigate',
		'sec-fetch-site': 'none',
		'sec-fetch-user': '?1',
		'upgrade-insecure-requests': '1'
	},
	'multiValueHeaders': {
		'Content-Length': ['0'],
		'Host': ['an_api_id.execute-api.aws_region.amazonaws.com'],
		'User-Agent': ['a_user_agent'],
		'X-Amzn-Trace-Id': ['an_amzn_trace_id'],
		'X-Forwarded-For': ['an_ip_address'],
		'X-Forwarded-Port': ['443'],
		'X-Forwarded-Proto': ['https'],
		'accept': ['text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'],
		'accept-encoding': ['gzip, deflate, br'],
		'accept-language': ['en-US,en;q=0.9'],
		'sec-ch-ua': ['" Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"'],
		'sec-ch-ua-mobile': ['?0'],
		'sec-ch-ua-platform': ['"Windows"'],
		'sec-fetch-dest': ['document'],
		'sec-fetch-mode': ['navigate'],
		'sec-fetch-site': ['none'],
		'sec-fetch-user': ['?1'],
		'upgrade-insecure-requests': ['1']
	},
	'queryStringParameters': None,
	'multiValueQueryStringParameters': None,
	'requestContext': {
		'accountId': 'an_aws_account',
		'apiId': 'an_api_id',
		'domainName': 'an_api_id.execute-api.aws_region.amazonaws.com',
		'domainPrefix': 'an_api_id',
		'extendedRequestId': 'a_request_id',
		'httpMethod': 'GET',
		'identity': {
			'accessKey': None,
			'accountId': None,
			'caller': None,
			'cognitoAmr': None,
			'cognitoAuthenticationProvider': None,
			'cognitoAuthenticationType': None,
			'cognitoIdentityId': None,
			'cognitoIdentityPoolId': None,
			'principalOrgId': None,
			'sourceIp': 'an_ip_address',
			'user': None,
			'userAgent': 'some_user_agent',
			'userArn': None
		},
		'path': '/default/redirect/google',
		'protocol': 'HTTP/1.1',
		'requestId': 'asdf',
		'requestTime': '02/Dec/2021:02:12:13 +0000',
		'requestTimeEpoch': 1638411133232,
		'resourceId': 'GET /redirect/{proxy+}',
		'resourcePath': '/redirect/{proxy+}',
		'stage': 'default'
	},
	'pathParameters': {
		'proxy': 'google'
	},
	'stageVariables': None,
	'body': None,
	'isBase64Encoded': False
}